export const seedProducts = [
  {
    id: 'prod-001',
    name_en: 'Ameerat Al Arab',
    name_fr: 'Ameerat Al Arab',
    name_ar: 'أميرات العرب',
    description_en: 'A graceful unisex fragrance by Asdaaf that draws inspiration from Arabian royalty. Opens with a bright burst of citrus and bergamot, evolving into a soft heart of white musk and aloe vera, before settling on a rich base of jasmine, musk, and oud.',
    description_fr: 'Un parfum mixte élégant d\'Asdaaf inspiré de la royauté arabique. S\'ouvre sur un éclat d\'agrumes et de bergamote, évoluant vers un cœur doux de musc blanc et d\'aloès, avant de se poser sur une base riche de jasmin, musc et oud.',
    description_ar: 'عطر مميز للجنسين من أصداف مستوحى من الأناقة العربية الراقية. يفتح بانتعاش الحمضيات والبرغموت، وينتقل إلى قلب ناعم من المسك الأبيض والألوفيرا، ليستقر على قاعدة غنية من الياسمين والمسك والعود.',
    price: 170,
    original_price: 200,
    images: [
      'https://www.intenseoud.com/cdn/shop/files/Untitleddesign-2024-01-26T101017.997.png?v=1774613584',
      'https://www.intenseoud.com/cdn/shop/files/Untitleddesign-2024-01-26T101027.380.png?v=1774613588',
      'https://www.intenseoud.com/cdn/shop/files/Untitleddesign-2024-01-26T101034.965.png?v=1774613595',
    ],
    category: 'unisex',
    brand: 'Asdaaf',
    volume_options: ['100ml'],
    scent_notes: {
      top: ['Citrus', 'Bergamot'],
      middle: ['White Musk', 'Aloe Vera'],
      base: ['Jasmine', 'Musk', 'Oud'],
    },
    quantity: 30,
    is_featured: true,
    is_bestseller: false,
    rating: 4.5,
    review_count: 88,
    created_at: '2025-01-10T10:00:00Z',
  },
  {
    id: 'prod-002',
    name_en: 'Habik',
    name_fr: 'Habik',
    name_ar: 'حبيك',
    description_en: 'A bold and captivating masculine fragrance by Lattafa. Opens with a dynamic blend of cardamom, bergamot, and pepper for a spicy-citrus introduction, evolving into a woody aromatic heart, and finishing with a warm, musky base.',
    description_fr: 'Un parfum masculin audacieux et captivant de Lattafa. S\'ouvre sur un mélange dynamique de cardamome, bergamote et poivre, évoluant vers un cœur aromatique boisé, avec une base chaude et musquée.',
    description_ar: 'عطر رجالي جريء وساحر من لطافة. يبدأ بمزيج ديناميكي من الهيل والبرغموت والفلفل، وينتقل إلى قلب عطري خشبي، ليختتم بقاعدة دافئة ومسكية.',
    price: 290,
    original_price: 350,
    images: [
      'https://www.lattafa-usa.com/cdn/shop/files/1_baf250d5-708c-425a-a3c7-94c3ea2d274c.png?v=1756361768',
      'https://www.lattafa-usa.com/cdn/shop/files/2_01e37470-dcdd-4c06-aacb-338fa4102931.png?v=1756361768',
      'https://www.lattafa-usa.com/cdn/shop/files/3_5d9e1808-5b00-4b91-9ad5-46ad6bbcd6ef.png?v=1756361768',
    ],
    category: 'men',
    brand: 'Lattafa',
    volume_options: ['100ml'],
    scent_notes: {
      top: ['Cardamom', 'Bergamot', 'Pepper'],
      middle: ['Iris', 'Woody Notes'],
      base: ['Vetiver', 'Musk', 'Amber'],
    },
    quantity: 25,
    is_featured: false,
    is_bestseller: true,
    rating: 4.6,
    review_count: 113,
    created_at: '2025-02-05T10:00:00Z',
  },
  {
    id: 'prod-003',
    name_en: 'Vulcan Feu',
    name_fr: 'Vulcan Feu',
    name_ar: 'فولكان فيو',
    description_en: 'A fiery and exotic unisex creation by French Avenue. An electrifying opening of mango, lemon, and ginger ignites into a heart of jasmine, violet, and pink pepper, before cooling into a sensual base of tonka bean, cedarwood, and ambergris.',
    description_fr: 'Une création mixte ardente et exotique de French Avenue. Une ouverture électrisante de mangue, citron et gingembre s\'embrase vers un cœur de jasmin, violette et poivre rose, avant de se fondre dans une base sensuelle de fève tonka, cèdre et ambre gris.',
    description_ar: 'إبداع متفجر وعالمي من فرنش أفينيو للجنسين. افتتاح مبهج بالمانجو والليمون والزنجبيل يتصاعد إلى قلب من الياسمين والبنفسج والفلفل الوردي، ليستقر على قاعدة حسية من حبة التونكا وخشب الأرز والعنبر.',
    price: 320,
    original_price: null,
    images: [
      'https://frenchavenue.com/cdn/shop/files/1_adefc13c-6803-433a-8ef5-b3aac7d179e2.jpg?v=1751985860',
      'https://frenchavenue.com/cdn/shop/files/5_1623f93b-b54e-48ec-90eb-14470f2d9267.jpg?v=1751985860',
      'https://frenchavenue.com/cdn/shop/files/4_4f7f2eef-dede-4e61-8fe5-ad325f9123fd.jpg?v=1751985860',
    ],
    category: 'unisex',
    brand: 'French Avenue',
    volume_options: ['100ml'],
    scent_notes: {
      top: ['Mango', 'Lemon', 'Ginger'],
      middle: ['Jasmine', 'Violet', 'Pink Pepper'],
      base: ['Tonka Bean', 'Cedarwood', 'Ambergris'],
    },
    quantity: 20,
    is_featured: true,
    is_bestseller: false,
    rating: 4.7,
    review_count: 72,
    created_at: '2025-03-01T10:00:00Z',
  },
  {
    id: 'prod-004',
    name_en: 'Teriaq Intense',
    name_fr: 'Teriaq Intense',
    name_ar: 'ترياق إنتنس',
    description_en: 'A richly complex unisex masterpiece by Lattafa. Created by master perfumer Quentin Bisch, this opulent oriental fragrance weaves saffron and bergamot over a spiced heart of cinnamon and plum, settling into a warm, addictive base of tonka bean, amber, and benzoin.',
    description_fr: 'Un chef-d\'œuvre unisexe richement complexe de Lattafa. Créé par le maître parfumeur Quentin Bisch, ce parfum oriental opulent tisse du safran et de la bergamote sur un cœur épicé de cannelle et de prune, pour une base chaude de fève tonka, d\'ambre et de benjoin.',
    description_ar: 'تحفة فنية معقدة وغنية للجنسين من لطافة، من إبداع العطار الأستاذ كونتان بيش. يجمع هذا العطر الشرقي الفاخر بين الزعفران والبرغموت على قلب متبل من القرفة والبرقوق، ليستقر على قاعدة دافئة ومعتقة من التونكا والعنبر والبنزوين.',
    price: 350,
    original_price: null,
    images: [
      'https://www.lattafa-usa.com/cdn/shop/files/Teriaq-Intense-1_b9408dff-5346-4542-a598-cfffb8454d81.png?v=1747416499',
      'https://www.lattafa-usa.com/cdn/shop/files/Teriaq-Intense-2_0fa56d59-4606-461a-83a9-3eb2f18204ff.png?v=1747416499',
      'https://www.lattafa-usa.com/cdn/shop/files/Teriaq-Intense-3_bd446110-92a1-4501-b132-7de36afaceb9.png?v=1747416499',
    ],
    category: 'unisex',
    brand: 'Lattafa',
    volume_options: ['100ml'],
    scent_notes: {
      top: ['Saffron', 'Bergamot'],
      middle: ['Cinnamon', 'Plum', 'Rose'],
      base: ['Tonka Bean', 'Amber', 'Benzoin'],
    },
    quantity: 18,
    is_featured: true,
    is_bestseller: true,
    rating: 4.9,
    review_count: 201,
    created_at: '2025-01-20T10:00:00Z',
  },
  {
    id: 'prod-005',
    name_en: "Ra'ed Oud",
    name_fr: "Ra'ed Oud",
    name_ar: 'رائد عود',
    description_en: "A commanding unisex oud fragrance by Lattafa. The opening of saffron, bergamot, and lavender gives way to a smoky heart of cypriol, rose, and incense, anchored by a deep, lasting base of leather, oud, sandalwood, and amber.",
    description_fr: "Un parfum d'oud mixte imposant de Lattafa. L'ouverture de safran, bergamote et lavande laisse place à un cœur fumé de cypriol, rose et encens, ancré par une base profonde de cuir, oud, santal et ambre.",
    description_ar: 'عطر عود راقٍ للجنسين من لطافة. يفتح بالزعفران والبرغموت واللافندر، وينتقل إلى قلب دخاني من السيبريول والورد والبخور، مستقراً على قاعدة عميقة من الجلد والعود والصندل والعنبر.',
    price: 190,
    original_price: null,
    images: [
      'https://www.lattafa-usa.com/cdn/shop/files/1_738e1688-2157-4999-9356-c6a2122a7b80.png?v=1756362071',
      'https://www.lattafa-usa.com/cdn/shop/files/2_38cb35d3-f7c4-47ea-97ee-a540ee6ced6b.png?v=1756362071',
      'https://www.lattafa-usa.com/cdn/shop/files/3_8c865c34-a28e-485a-bd21-5098c3042854.png?v=1756362071',
    ],
    category: 'oud',
    brand: 'Lattafa',
    volume_options: ['100ml'],
    scent_notes: {
      top: ['Saffron', 'Bergamot', 'Lavender'],
      middle: ['Cypriol', 'Rose', 'Incense'],
      base: ['Leather', 'Oud', 'Sandalwood', 'Amber'],
    },
    quantity: 22,
    is_featured: false,
    is_bestseller: true,
    rating: 4.6,
    review_count: 134,
    created_at: '2025-02-15T10:00:00Z',
  },
  {
    id: 'prod-006',
    name_en: "Bade'e Al Oud",
    name_fr: "Bade'e Al Oud",
    name_ar: 'بديع العود',
    description_en: "A iconic oud fragrance by Lattafa that has captivated connoisseurs worldwide. Rich saffron and black pepper open the composition, leading to a powerful heart of patchouli and oud layered with rose, resting on a majestic base of amber, musk, and sandalwood.",
    description_fr: "Un parfum d'oud emblématique de Lattafa qui a captivé les connaisseurs du monde entier. Le safran riche et le poivre noir ouvrent la composition, menant à un cœur puissant de patchouli et d'oud avec de la rose, sur une base majestueuse d'ambre, musc et santal.",
    description_ar: 'عطر عود أيقوني من لطافة أسر محبي العطور حول العالم. يفتح بالزعفران الغني والفلفل الأسود، وينتقل إلى قلب قوي من الباتشولي والعود والورد، على قاعدة مهيبة من العنبر والمسك والصندل.',
    price: 220,
    original_price: 250,
    images: [
      'https://www.lattafa-usa.com/cdn/shop/files/1_5a4baf04-76ee-43c9-9751-4ac43d7aba74.png?v=1747556003',
      'https://www.lattafa-usa.com/cdn/shop/files/2_7f7a2c86-3138-4e61-a04d-56907552a5aa.png?v=1747556003',
      'https://www.lattafa-usa.com/cdn/shop/files/Badee-Al-Oud-Honor-_-Glory-1_a3e5a0eb-fe3d-4799-8408-2874e3a642fa.png?v=1747415524',
    ],
    category: 'oud',
    brand: 'Lattafa',
    volume_options: ['100ml'],
    scent_notes: {
      top: ['Saffron', 'Black Pepper'],
      middle: ['Patchouli', 'Oud', 'Rose'],
      base: ['Amber', 'Musk', 'Sandalwood'],
    },
    quantity: 28,
    is_featured: true,
    is_bestseller: true,
    rating: 4.8,
    review_count: 178,
    created_at: '2025-01-05T10:00:00Z',
  },
  {
    id: 'prod-007',
    name_en: 'Khamrah Qahwa',
    name_fr: 'Khamrah Qahwa',
    name_ar: 'خمرة قهوة',
    description_en: "A warm and seductive unisex fragrance by Lattafa inspired by Arabian coffee ceremonies. Cinnamon, cardamom, and ginger lead into a sweet praline heart with white florals, melting into a rich, velvety base of coffee, vanilla, tonka bean, and musk.",
    description_fr: "Un parfum mixte chaud et séduisant de Lattafa inspiré des cérémonies du café arabe. La cannelle, la cardamome et le gingembre mènent vers un cœur de praline avec des floraux blancs, fondant dans une base veloutée de café, vanille, tonka et musc.",
    description_ar: 'عطر دافئ ومغوٍ للجنسين من لطافة مستوحى من طقوس القهوة العربية. يبدأ بالقرفة والهيل والزنجبيل ثم ينتقل إلى قلب حلو من البرالين والزهور البيضاء، ليذوب في قاعدة مخملية من القهوة والفانيليا والتونكا والمسك.',
    price: 260,
    original_price: null,
    images: [
      'https://www.lattafa-usa.com/cdn/shop/files/Khamrah-Qahwa-1_a2c9fdc2-8264-4da1-83e2-e5e065cecd53.png?v=1747416095',
      'https://www.lattafa-usa.com/cdn/shop/files/Khamrah-Qahwa-2_18e1e5f1-4f51-4325-83af-2d625beb976a.png?v=1747416096',
      'https://www.lattafa-usa.com/cdn/shop/files/Khamrah-Qahwa-3_fc8954fb-9ed2-4bcc-974a-d87f75101383.png?v=1747416095',
    ],
    category: 'unisex',
    brand: 'Lattafa',
    volume_options: ['100ml'],
    scent_notes: {
      top: ['Cinnamon', 'Cardamom', 'Ginger'],
      middle: ['Praline', 'White Flowers'],
      base: ['Coffee', 'Vanilla', 'Tonka Bean', 'Musk'],
    },
    quantity: 35,
    is_featured: true,
    is_bestseller: true,
    rating: 4.8,
    review_count: 225,
    created_at: '2025-01-25T10:00:00Z',
  },
  {
    id: 'prod-008',
    name_en: 'Asad Elixir',
    name_fr: 'Asad Elixir',
    name_ar: 'أسد إكسير',
    description_en: "A dark and commanding masculine elixir by Lattafa. Presented in a signature matte black bottle adorned with a lion motif, this spicy-woody composition opens with bold spices and pepper, journeys through a leather and oud heart, and settles into a deep base of amber and musk.",
    description_fr: "Un élixir masculin sombre et imposant de Lattafa. Présenté dans un flacon noir mat orné d'un motif lion, cette composition épicée-boisée s'ouvre sur des épices audacieuses et du poivre, traverse un cœur de cuir et d'oud, et se pose sur une base profonde d'ambre et de musc.",
    description_ar: 'إكسير رجالي داكن وقوي من لطافة. مقدم في قارورة سوداء مطفأة مزينة بنقش الأسد، يفتح هذا العطر بتوابل جريئة وفلفل، وينتقل عبر قلب من الجلد والعود، ليستقر في قاعدة عميقة من العنبر والمسك.',
    price: 199,
    original_price: 250,
    images: [
      'https://www.lattafa-usa.com/cdn/shop/files/ASADELIXIRBOTTLE.png?v=1760805808',
      'https://www.lattafa-usa.com/cdn/shop/files/ASADELIXIRBOTTLE_2.png?v=1760805808',
      'https://www.lattafa-usa.com/cdn/shop/files/AsadElixirBox.png?v=1760805808',
    ],
    category: 'men',
    brand: 'Lattafa',
    volume_options: ['100ml'],
    scent_notes: {
      top: ['Spices', 'Black Pepper'],
      middle: ['Leather', 'Oud'],
      base: ['Amber', 'Musk', 'Woody Notes'],
    },
    quantity: 20,
    is_featured: false,
    is_bestseller: true,
    rating: 4.7,
    review_count: 96,
    created_at: '2025-03-10T10:00:00Z',
  },
  {
    id: 'prod-009',
    name_en: 'Asad Bourbon',
    name_fr: 'Asad Bourbon',
    name_ar: 'أسد بوربون',
    description_en: "An elegant masculine fragrance by Lattafa inspired by the refinement of bourbon. Vibrant top notes of lavender, mirabelle, and pink pepper open into a warm heart of cacao, nutmeg, and davana, finishing with a luxurious, long-lasting base of bourbon vanilla, amber, and vetiver.",
    description_fr: "Un parfum masculin élégant de Lattafa inspiré par le raffinement du bourbon. Des notes de tête vibrantes de lavande, mirabelle et poivre rose s'ouvrent sur un cœur chaud de cacao, muscade et davana, pour finir avec une base luxueuse de vanille bourbon, ambre et vétiver.",
    description_ar: 'عطر رجالي أنيق من لطافة مستوحى من رقي البوربون. يفتح بلافندر حيوي وإجاص ميرابيل وفلفل وردي، وينتقل إلى قلب دافئ من الكاكاو وجوزة الطيب والدافانا، ليختتم بقاعدة فاخرة من فانيليا البوربون والعنبر والفيتيفر.',
    price: 199,
    original_price: 250,
    images: [
      'https://www.lattafa-usa.com/cdn/shop/files/Asad-Bourbon-1.png?v=1747416709',
      'https://www.lattafa-usa.com/cdn/shop/files/Asad-Bourbon-2.png?v=1747416709',
      'https://www.lattafa-usa.com/cdn/shop/files/Asad-Bourbon-3.png?v=1747416709',
    ],
    category: 'men',
    brand: 'Lattafa',
    volume_options: ['100ml'],
    scent_notes: {
      top: ['Lavender', 'Mirabelle', 'Pink Pepper'],
      middle: ['Cacao', 'Nutmeg', 'Davana'],
      base: ['Bourbon Vanilla', 'Amber', 'Vetiver'],
    },
    quantity: 20,
    is_featured: true,
    is_bestseller: true,
    rating: 4.8,
    review_count: 141,
    created_at: '2025-02-20T10:00:00Z',
  },
]
