export const seedProducts = [
  {
    id: 'prod-001',
    name_en: 'Royal Oud Noir',
    name_fr: 'Oud Royal Noir',
    name_ar: 'العود الملكي الأسود',
    description_en: 'A majestic blend of rare Cambodian oud, smoky incense, and velvety rose. This opulent fragrance opens with a burst of saffron and bergamot, evolving into a rich heart of oud and Bulgarian rose, before settling into a warm base of amber, musk, and sandalwood.',
    description_fr: 'Un mélange majestueux d\'oud cambodgien rare, d\'encens fumé et de rose veloutée. Ce parfum opulent s\'ouvre sur un éclat de safran et de bergamote, évoluant vers un cœur riche d\'oud et de rose bulgare, avant de se poser sur une base chaude d\'ambre, de musc et de bois de santal.',
    description_ar: 'مزيج ملكي من العود الكمبودي النادر والبخور المدخن والورد المخملي. يفتتح هذا العطر الفاخر بانفجار من الزعفران والبرغموت، ليتطور إلى قلب غني من العود والورد البلغاري، قبل أن يستقر على قاعدة دافئة من العنبر والمسك وخشب الصندل.',
    price: 18500,
    original_price: 22000,
    images: [
      'https://images.unsplash.com/photo-1594035910387-fea081e59eb0?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop',
    ],
    category: 'oud',
    brand: 'Maison Arabique',
    volume_options: ['30ml', '50ml', '100ml'],
    scent_notes: {
      top: ['Saffron', 'Bergamot'],
      middle: ['Oud', 'Bulgarian Rose'],
      base: ['Amber', 'Musk', 'Sandalwood'],
    },
    quantity: 25,
    is_featured: true,
    is_bestseller: true,
    rating: 4.8,
    review_count: 142,
    created_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'prod-002',
    name_en: 'Velvet Rose & Amber',
    name_fr: 'Rose Velours & Ambre',
    name_ar: 'الورد المخملي والعنبر',
    description_en: 'An intoxicating feminine fragrance that captures the essence of a midnight garden. Lush Damascena rose intertwines with warm amber and a whisper of vanilla, creating an alluring trail that lingers beautifully.',
    description_fr: 'Un parfum féminin enivrant qui capture l\'essence d\'un jardin de minuit. La rose de Damas luxuriante s\'entrelace avec l\'ambre chaud et un murmure de vanille, créant un sillage séduisant qui perdure magnifiquement.',
    description_ar: 'عطر أنثوي ساحر يلتقط جوهر حديقة منتصف الليل. وردة الدمشق الفاخرة تتشابك مع العنبر الدافئ وهمسة من الفانيليا، لتخلق أثراً جذاباً يدوم بشكل جميل.',
    price: 14200,
    original_price: null,
    images: [
      'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1595425964072-537c688e3b7a?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&h=800&fit=crop',
    ],
    category: 'women',
    brand: 'Fleur de Luxe',
    volume_options: ['30ml', '50ml', '100ml'],
    scent_notes: {
      top: ['Pink Pepper', 'Pear'],
      middle: ['Damascena Rose', 'Peony'],
      base: ['Amber', 'Vanilla', 'White Musk'],
    },
    quantity: 40,
    is_featured: true,
    is_bestseller: true,
    rating: 4.7,
    review_count: 98,
    created_at: '2025-02-10T10:00:00Z',
  },
  {
    id: 'prod-003',
    name_en: 'Gentleman\'s Reserve',
    name_fr: 'Réserve du Gentleman',
    name_ar: 'محمية الجنتلمان',
    description_en: 'A distinguished masculine composition that speaks of refined taste and quiet confidence. Spicy cardamom and fresh grapefruit give way to a heart of iris and violet leaf, resting on a foundation of leather, vetiver, and precious woods.',
    description_fr: 'Une composition masculine distinguée qui parle de goût raffiné et de confiance tranquille. La cardamome épicée et le pamplemousse frais cèdent la place à un cœur d\'iris et de feuille de violette, reposant sur une base de cuir, de vétiver et de bois précieux.',
    description_ar: 'تركيبة رجالية مميزة تتحدث عن الذوق الرفيع والثقة الهادئة. الهيل المتبل والجريب فروت الطازج يفسحان المجال لقلب من السوسن وأوراق البنفسج، مستقرة على أساس من الجلد والفيتيفر والأخشاب الثمينة.',
    price: 12800,
    original_price: 15000,
    images: [
      'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1594035910387-fea081e59eb0?w=600&h=800&fit=crop',
    ],
    category: 'men',
    brand: 'Heritage & Co.',
    volume_options: ['50ml', '100ml'],
    scent_notes: {
      top: ['Cardamom', 'Grapefruit', 'Juniper'],
      middle: ['Iris', 'Violet Leaf'],
      base: ['Leather', 'Vetiver', 'Cedarwood'],
    },
    quantity: 35,
    is_featured: true,
    is_bestseller: false,
    rating: 4.5,
    review_count: 76,
    created_at: '2025-03-05T10:00:00Z',
  },
  {
    id: 'prod-004',
    name_en: 'Mediterranean Breeze',
    name_fr: 'Brise Méditerranéenne',
    name_ar: 'نسيم البحر المتوسط',
    description_en: 'A fresh and vibrant unisex fragrance inspired by the sun-drenched coasts of the Mediterranean. Citrus-forward with aquatic undertones, this scent captures the feeling of warm sea breeze on sunlit skin.',
    description_fr: 'Un parfum mixte frais et vibrant inspiré des côtes ensoleillées de la Méditerranée. Dominé par les agrumes avec des nuances aquatiques, ce parfum capture la sensation de la brise marine chaude sur la peau ensoleillée.',
    description_ar: 'عطر منعش ونابض بالحياة للجنسين مستوحى من سواحل البحر الأبيض المتوسط المشمسة. بنوتات حمضية أمامية ولمسات مائية، يلتقط هذا العطر إحساس نسيم البحر الدافئ على البشرة المشمسة.',
    price: 9800,
    original_price: null,
    images: [
      'https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1594035910387-fea081e59eb0?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=800&fit=crop',
    ],
    category: 'unisex',
    brand: 'Côte Azur',
    volume_options: ['30ml', '50ml', '100ml'],
    scent_notes: {
      top: ['Lemon', 'Bergamot', 'Sea Salt'],
      middle: ['Jasmine', 'White Tea'],
      base: ['Driftwood', 'White Musk', 'Ambergris'],
    },
    quantity: 60,
    is_featured: false,
    is_bestseller: true,
    rating: 4.6,
    review_count: 112,
    created_at: '2025-04-12T10:00:00Z',
  },
  {
    id: 'prod-005',
    name_en: 'Midnight Orchid',
    name_fr: 'Orchidée de Minuit',
    name_ar: 'أوركيد منتصف الليل',
    description_en: 'A darkly seductive women\'s fragrance built around exotic black orchid and rich dark chocolate. Opulent and mysterious, it weaves together night-blooming flowers with smoky incense and deep vanilla.',
    description_fr: 'Un parfum féminin sombrement séduisant construit autour de l\'orchidée noire exotique et du chocolat noir riche. Opulent et mystérieux, il tisse ensemble des fleurs nocturnes avec de l\'encens fumé et de la vanille profonde.',
    description_ar: 'عطر نسائي مغوٍ بشكل داكن مبني حول الأوركيد الأسود الغريب والشوكولاتة الداكنة الغنية. فاخر وغامض، ينسج معاً أزهار الليل مع البخور المدخن والفانيليا العميقة.',
    price: 16500,
    original_price: 19000,
    images: [
      'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1595425964072-537c688e3b7a?w=600&h=800&fit=crop',
    ],
    category: 'women',
    brand: 'Noir Essence',
    volume_options: ['30ml', '50ml', '100ml'],
    scent_notes: {
      top: ['Black Pepper', 'Mandarin'],
      middle: ['Black Orchid', 'Jasmine Sambac'],
      base: ['Dark Chocolate', 'Vanilla', 'Patchouli'],
    },
    quantity: 3,
    is_featured: true,
    is_bestseller: true,
    rating: 4.9,
    review_count: 203,
    created_at: '2025-01-20T10:00:00Z',
  },
  {
    id: 'prod-006',
    name_en: 'Sultan\'s Gold',
    name_fr: 'Or du Sultan',
    name_ar: 'ذهب السلطان',
    description_en: 'An opulent oud fragrance fit for royalty. Rare Indian oud is blended with precious saffron threads and Taif rose, creating a rich and commanding presence that demands attention.',
    description_fr: 'Un parfum d\'oud opulent digne de la royauté. L\'oud indien rare est mélangé avec des fils de safran précieux et de la rose de Taif, créant une présence riche et imposante qui commande l\'attention.',
    description_ar: 'عطر عود فاخر يليق بالملوك. عود هندي نادر ممزوج بخيوط الزعفران الثمينة وورد الطائف، يخلق حضوراً غنياً وقوياً يستقطب الانتباه.',
    price: 24000,
    original_price: null,
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1594035910387-fea081e59eb0?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&h=800&fit=crop',
    ],
    category: 'oud',
    brand: 'Maison Arabique',
    volume_options: ['30ml', '50ml'],
    scent_notes: {
      top: ['Saffron', 'Cardamom'],
      middle: ['Taif Rose', 'Indian Oud'],
      base: ['Sandalwood', 'Musk', 'Benzoin'],
    },
    quantity: 15,
    is_featured: true,
    is_bestseller: false,
    rating: 4.7,
    review_count: 67,
    created_at: '2025-05-01T10:00:00Z',
  },
  {
    id: 'prod-007',
    name_en: 'Ocean Whisper',
    name_fr: 'Murmure de l\'Océan',
    name_ar: 'همس المحيط',
    description_en: 'A clean, modern unisex scent that captures the essence of ocean air. Fresh marine notes blend with white florals and a grounding base of mineral accord and driftwood.',
    description_fr: 'Un parfum mixte propre et moderne qui capture l\'essence de l\'air océanique. Des notes marines fraîches se mêlent à des fleurs blanches et une base stabilisante d\'accord minéral et de bois flotté.',
    description_ar: 'عطر نظيف وعصري للجنسين يلتقط جوهر هواء المحيط. نوتات بحرية منعشة تمتزج مع الأزهار البيضاء وقاعدة مستقرة من الاتفاق المعدني والخشب الطافي.',
    price: 8500,
    original_price: null,
    images: [
      'https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop',
    ],
    category: 'unisex',
    brand: 'Côte Azur',
    volume_options: ['30ml', '50ml', '100ml'],
    scent_notes: {
      top: ['Sea Breeze', 'Citrus Zest'],
      middle: ['Lily of the Valley', 'White Iris'],
      base: ['Driftwood', 'Mineral Accord', 'Musk'],
    },
    quantity: 45,
    is_featured: false,
    is_bestseller: false,
    rating: 4.3,
    review_count: 54,
    created_at: '2025-06-10T10:00:00Z',
  },
  {
    id: 'prod-008',
    name_en: 'Noir Absolu',
    name_fr: 'Noir Absolu',
    name_ar: 'نوار أبسولو',
    description_en: 'A bold and magnetic men\'s fragrance that embodies modern sophistication. Dark leather and smoky vetiver are illuminated by bright bergamot, with a seductive base of tonka bean and black amber.',
    description_fr: 'Un parfum masculin audacieux et magnétique qui incarne la sophistication moderne. Le cuir sombre et le vétiver fumé sont illuminés par la bergamote brillante, avec une base séduisante de fève tonka et d\'ambre noir.',
    description_ar: 'عطر رجالي جريء ومغناطيسي يجسد الرقي العصري. الجلد الداكن والفيتيفر المدخن يضيئهما البرغموت اللامع، مع قاعدة مغوية من حبوب التونكا والعنبر الأسود.',
    price: 13500,
    original_price: 16000,
    images: [
      'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1594035910387-fea081e59eb0?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=600&h=800&fit=crop',
    ],
    category: 'men',
    brand: 'Noir Essence',
    volume_options: ['50ml', '100ml'],
    scent_notes: {
      top: ['Bergamot', 'Black Pepper'],
      middle: ['Leather', 'Smoky Vetiver'],
      base: ['Tonka Bean', 'Black Amber', 'Oud'],
    },
    quantity: 2,
    is_featured: false,
    is_bestseller: true,
    rating: 4.6,
    review_count: 89,
    created_at: '2025-03-18T10:00:00Z',
  },
  {
    id: 'prod-009',
    name_en: 'Jardin de Fleurs',
    name_fr: 'Jardin de Fleurs',
    name_ar: 'حديقة الأزهار',
    description_en: 'A luminous floral bouquet that celebrates the beauty of a French garden in full bloom. Delicate peony and fresh lily mingle with green stems and dewy morning air, resting on a soft bed of white musk.',
    description_fr: 'Un bouquet floral lumineux qui célèbre la beauté d\'un jardin français en pleine floraison. La pivoine délicate et le lys frais se mêlent aux tiges vertes et à l\'air frais du matin, reposant sur un lit doux de musc blanc.',
    description_ar: 'باقة زهرية مضيئة تحتفي بجمال حديقة فرنسية في كامل إزهارها. الفاوانيا الرقيقة والزنبق الطازج يمتزجان مع السيقان الخضراء وهواء الصباح الندي، مستقرة على فراش ناعم من المسك الأبيض.',
    price: 11200,
    original_price: null,
    images: [
      'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1595425964072-537c688e3b7a?w=600&h=800&fit=crop',
    ],
    category: 'women',
    brand: 'Fleur de Luxe',
    volume_options: ['30ml', '50ml', '100ml'],
    scent_notes: {
      top: ['Green Apple', 'Lemon Verbena'],
      middle: ['Peony', 'Lily', 'Freesia'],
      base: ['White Musk', 'Cedar', 'Moss'],
    },
    quantity: 50,
    is_featured: false,
    is_bestseller: false,
    rating: 4.4,
    review_count: 43,
    created_at: '2025-07-01T10:00:00Z',
  },
  {
    id: 'prod-010',
    name_en: 'Heritage Leather',
    name_fr: 'Cuir Héritage',
    name_ar: 'إرث الجلد',
    description_en: 'A timeless masculine classic reimagined. Rich leather meets aromatic lavender and warm tobacco, creating a sophisticated scent that evokes the ambiance of a gentleman\'s private library.',
    description_fr: 'Un classique masculin intemporel réimaginé. Le cuir riche rencontre la lavande aromatique et le tabac chaud, créant un parfum sophistiqué qui évoque l\'ambiance de la bibliothèque privée d\'un gentleman.',
    description_ar: 'كلاسيكي رجالي خالد أُعيد تصوره. الجلد الغني يلتقي مع اللافندر العطري والتبغ الدافئ، ليخلق عطراً راقياً يستحضر أجواء مكتبة الجنتلمان الخاصة.',
    price: 15800,
    original_price: null,
    images: [
      'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1594035910387-fea081e59eb0?w=600&h=800&fit=crop',
    ],
    category: 'men',
    brand: 'Heritage & Co.',
    volume_options: ['50ml', '100ml'],
    scent_notes: {
      top: ['Lavender', 'Thyme', 'Bergamot'],
      middle: ['Leather', 'Geranium'],
      base: ['Tobacco', 'Tonka Bean', 'Amber'],
    },
    quantity: 4,
    is_featured: false,
    is_bestseller: false,
    rating: 4.5,
    review_count: 61,
    created_at: '2025-02-28T10:00:00Z',
  },
  {
    id: 'prod-011',
    name_en: 'Essence du Désert',
    name_fr: 'Essence du Désert',
    name_ar: 'عطر الصحراء',
    description_en: 'A warm and enveloping unisex fragrance inspired by desert nights. Precious frankincense and myrrh blend with spiced saffron and a hint of date, creating an exotic and comforting aura.',
    description_fr: 'Un parfum mixte chaud et enveloppant inspiré des nuits du désert. L\'encens précieux et la myrrhe se mêlent au safran épicé et à une touche de datte, créant une aura exotique et réconfortante.',
    description_ar: 'عطر دافئ وغامر للجنسين مستوحى من ليالي الصحراء. اللبان الثمين والمر يمتزجان مع الزعفران المتبل ولمسة من التمر، ليخلقا هالة غريبة ومريحة.',
    price: 17500,
    original_price: 20000,
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=800&fit=crop',
    ],
    category: 'unisex',
    brand: 'Maison Arabique',
    volume_options: ['30ml', '50ml', '100ml'],
    scent_notes: {
      top: ['Saffron', 'Pink Pepper'],
      middle: ['Frankincense', 'Myrrh', 'Date'],
      base: ['Sandalwood', 'Amber', 'Vanilla'],
    },
    quantity: 20,
    is_featured: true,
    is_bestseller: true,
    rating: 4.8,
    review_count: 156,
    created_at: '2025-04-25T10:00:00Z',
  },
  {
    id: 'prod-012',
    name_en: 'Luxury Gift Collection',
    name_fr: 'Collection Cadeau Luxe',
    name_ar: 'مجموعة هدايا فاخرة',
    description_en: 'An exquisite gift set featuring three of our most beloved miniature fragrances (15ml each): Royal Oud Noir, Velvet Rose & Amber, and Mediterranean Breeze. Presented in an elegant black and gold box.',
    description_fr: 'Un coffret cadeau exquis comprenant trois de nos miniatures de parfum les plus appréciées (15ml chacune) : Oud Royal Noir, Rose Velours & Ambre, et Brise Méditerranéenne. Présenté dans un élégant coffret noir et or.',
    description_ar: 'طقم هدايا رائع يضم ثلاثة من أحب عطورنا المصغرة (15 مل لكل منها): العود الملكي الأسود، الورد المخملي والعنبر، ونسيم البحر المتوسط. مقدم في صندوق أنيق أسود وذهبي.',
    price: 21000,
    original_price: 28000,
    images: [
      'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop',
    ],
    category: 'gift-sets',
    brand: 'Maison Arabique',
    volume_options: ['3x15ml'],
    scent_notes: {
      top: ['Saffron', 'Pink Pepper', 'Lemon'],
      middle: ['Rose', 'Oud', 'Jasmine'],
      base: ['Amber', 'Musk', 'Sandalwood'],
    },
    quantity: 30,
    is_featured: true,
    is_bestseller: false,
    rating: 4.9,
    review_count: 87,
    created_at: '2025-05-15T10:00:00Z',
  },
]
